package enums;

import java.util.Arrays;
import java.util.List;

public enum GoogleLanguages {

	af("Africâner"),
	sq("Albanês"),
	de("Alemão"),
	am("Amárico"),
	ar("Árabe"),
	hy("Armênio"),
	as("Assamês"),
	ay("Aymara"),
	az("Azerbaijano"),
	eu("Basco"),
	be("Bielorrusso"),
	bn("Bengali"),
	bho("Bhojpuri"),
	bs("Bósnio"),
	bg("Búlgaro"),
	ca("Catalão"),
	ceb("Cebuano"),
	zh_CN("Chinês (Simplificado)"),
	zh_TW("Chinês (Tradicional)"),
	co("Corso"),
	hr("Croata"),
	cs("Tcheco"),
	da("Dinamarquês"),
	dv("Dhivehi"),
	doi("Dogri"),
	nl("Holandês"),
	en("Inglês"),
	eo("Esperanto"),
	et("Estoniano"),
	ee("Ewe"),
	fil("Filipino (Tagalo)"),
	fi("Finlandês"),
	fr("Francês"),
	fy("Frísio"),
	gl("Galego"),
	ka("Georgiano"),
	el("Grego"),
	gn("Guarani"),
	gu("Gujarati"),
	ht("Crioulo haitiano"),
	ha("Hausa"),
	haw("Havaiano"),
	he("Hebraico"),
	hi("Hindi"),
	hmn("Hmong"),
	hu("Húngaro"),
	is("Islandês"),
	ig("Igbo"),
	ilo("Ilocano"),
	id("Indonésio"),
	ga("Irlandês"),
	it("Italiano"),
	ja("Japonês"),
	jv("Javanês"),
	kn("Kannada"),
	kk("Cazaque"),
	km("Khmer"),
	rw("Kinyarwanda"),
	gom("Konkani"),
	ko("Coreano"),
	kri("Krio"),
	ku("Curdo"),
	ckb("Curdo (Sorani)"),
	ky("Quirguiz"),
	lo("Laosiano"),
	la("Latim"),
	lv("Letão"),
	ln("Lingala"),
	lt("Lituano"),
	lg("Luganda"),
	lb("Luxemburguês"),
	mk("Macedônio"),
	mai("Maithili"),
	ms("Malaio"),
	ml("Malaiala"),
	mt("Maltês"),
	mi("Maori"),
	mr("Marathi"),
	mni_Mtei("Meiteilon (Manipuri)"),
	lus("Mizo"),
	mn("Mongol"),
	my("Birmanês"),
	ne("Nepalês"),
	no("Norueguês"),
	ny("Nyanja (Chichewa)"),
	or("Odia (Oriya)"),
	om("Oromo"),
	ps("Pashto"),
	fa("Persa"),
	pl("Polonês"),
	pt("Português (Português (Brasil))"),
	pa("Punjabi"),
	qu("Quechua"),
	ro("Romeno"),
	ru("Russo"),
	sm("Samoano"),
	sa("Sânscrito"),
	gd("Gaélico escocês"),
	nso("Sepedi"),
	sr("Sérvio"),
	st("Sesotho"),
	sn("Shona"),
	sd("Sindhi"),
	si("Cingalês"),
	sk("Eslovaco"),
	sl("Esloveno"),
	so("Somali"),
	es("Espanhol"),
	sw("Suaíli"),
	sv("Sueco"),
	tl("Tagalo (Filipino)"),
	tg("Tadjique"),
	ta("Tâmil"),
	tt("Tártaro"),
	te("Telugu"),
	th("Tailandês"),
	ti("Tigrínia"),
	ts("Tsonga"),
	tr("Turco"),
	tk("Turcomeno"),
	ak("Twi (Akan)"),
	uk("Ucraniano"),
	ur("Urdu"),
	ug("Uigur"),
	uz("Uzbeque"),
	vi("Vietnamita"),
	cy("Galês"),
	xh("Xhosa"),
	yi("Iídiche"),
	yo("Ioruba"),
	zu("Zulu");
	
	private String value;

	GoogleLanguages(String value)
		{ this.value = value; }
	
	public String getValue()
		{ return value; }
	
	public static List<GoogleLanguages> getListOfAll() {
		return Arrays.asList(af, sq, de, am, ar, hy, as, ay, az, eu, be, bn, bho, bs,
				bg, ca, ceb, zh_CN, zh_TW, co, hr, cs, da, dv, doi, nl, en, eo, et, ee,
				fil, fi, fr, fy, gl, ka, de, el, gn, gu, ht, ha, haw, he, hi, hmn, hu,
				is, ig, ilo, id, ga, it, ja, jv, kn, kk, km, rw, gom, ko, kri, ku, ckb,
				ky, lo, la, lv, ln, lt, lg, lb, mk, mai, ms, ml, mt, mi, mr, mni_Mtei,
				lus, mn, my, ne, no, ny, or, om, ps, fa, pl, pt, pa, qu, ro, ru, sm, sa,
				gd, nso, sr, st, sn, sd, si, sk, sl, so, es, sw, sv, tl, tg, ta, tt, te,
				th, ti, ts, tr, tk, ak, uk, ur, ug, uz, vi, cy, xh, yi, yo, zu);
	}
	
}
